<div style="background-color:#fff; padding:40px; display:flex; justify-content:center; align-items:center; font-family:Arial, sans-serif;">
  <div style="background-color:#ffffff; padding:30px; border-radius:12px; max-width:600px; width:100%; text-align:center; box-shadow:0 10px 25px rgba(0,0,0,0.15);margin:0 auto;">
      <img src="https://holosen.net/public/src/img/logo/holosen-logo.png" width="50"/>
    <p style="font-size:18px; font-weight:bold; color:#222222; line-height:1.8; margin-bottom:25px;text-align:justify">
     I prepared this code for the Holosen Artificial Intelligence 0-100 training course.
        <br/>
        For more detailed Persian training resources, you can visit:
    </p>
    <a href="https://holosen.net/artificial-intelligence/?src=kaggle" target="_blank" 
       style="display:inline-block; background-color:#525fe1; color:#ffffff; text-decoration:none; padding:14px 28px; border-radius:8px; font-size:16px; font-weight:bold;">
       Holosen Artificial Intelligence 0-100 Training Course
    </a>
  </div>
</div>

In [3]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, confusion_matrix, classification_report
)

# EDA + ETL

## Extract data

In [4]:
df=pd.read_csv('C:/Users/pc_parsian/Desktop/ml/data.csv')
df.head(5)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

## Explorarity Data Analysis

In [5]:
print("Shape:", df.shape)
df.info()

Shape: (569, 33)
<class 'pandas.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    str
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), str(1)
memory usage: 146.8 KB

In [6]:
df.isna().sum().sort_values(ascending=False).head(5)

Unnamed: 32                569
compactness_se               0
fractal_dimension_worst      0
symmetry_worst               0
concave points_worst         0
dtype: int64

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
id,569.0,3.037183e+07,1.250206e+08,8670.000000,869218.000000,906024.000000,8.813129e+06,9.113205e+08
radius_mean,569.0,1.412729e+01,3.524049e+00,6.981000,11.700000,13.370000,1.578000e+01,2.811000e+01
texture_mean,569.0,1.928965e+01,4.301036e+00,9.710000,16.170000,18.840000,2.180000e+01,3.928000e+01
perimeter_mean,569.0,9.196903e+01,2.429898e+01,43.790000,75.170000,86.240000,1.041000e+02,1.885000e+02
area_mean,569.0,6.548891e+02,3.519141e+02,143.500000,420.300000,551.100000,7.827000e+02,2.501000e+03
smoothness_mean,569.0,9.636028e-02,1.406413e-02,0.052630,0.086370,0.095870,1.053000e-01,1.634000e-01
compactness_mean,569.0,1.043410e-01,5.281276e-02,0.019380,0.064920,0.092630,1.304000e-01,3.454000e-01
concavity_mean,569.0,8.879932e-02,7.971981e-02,0.000000,0.029560,0.061540,1.307000e-01,4.268000e-01
concave points_mean,569.0,4.891915e-02,3.880284e-02,0.000000,0.020310,0.033500,7.400000e-02,2.012000e-01
symmetry_mean,569.0,1.811619e-01,2.741428e-02,0.106000,0.161900,0.179200,1.957000e-01,3.040000e-01
fractal_dimension_mean,569.0,6.279761e-02,7.060363e-03,0.049960,0.057700,0.061540,6.612000e-02,9.744000e-02
radius_se,569.0,4.051721e-01,2.773127e-01,0.111500,0.232400,0.324200,4.789000e-01,2.873000e+00
texture_se,569.0,1.216853e+00,5.516484e-01,0.360200,0.833900,1.108000,1.474000e+00,4.885000e+00
perimeter_se,569.0,2.866059e+00,2.021855e+00,0.757000,1.606000,2.287000,3.357000e+00,2.198000e+01
area_se,569.0,4.033708e+01,4.549101e+01,6.802000,17.850000,24.530000,4.519000e+01,5.422000e+02
smoothness_se,569.0,7.040979e-03,3.002518e-03,0.001713,0.005169,0.006380,8.146000e-03,3.113000e-02
compactness_se,569.0,2.547814e-02,1.790818e-02,0.002252,0.013080,0.020450,3.245000e-02,1.354000e-01
concavity_se,569.0,3.189372e-02,3.018606e-02,0.000000,0.015090,0.025890,4.205000e-02,3.960000e-01
concave points_se,569.0,1.179614e-02,6.170285e-03,0.000000,0.007638,0.010930,1.471000e-02,5.279000e-02
symmetry_se,569.0,2.054230e-02,8.266372e-03,0.007882,0.015160,0.018730,2.348000e-02,7.895000e-02
fractal_dimension_se,569.0,3.794904e-03,2.646071e-03,0.000895,0.002248,0.003187,4.558000e-03,2.984000e-02
radius_worst,569.0,1.626919e+01,4.833242e+00,7.930000,13.010000,14.970000,1.879000e+01,3.604000e+01
texture_worst,569.0,2.567722e+01,6.146258e+00,12.020000,21.080000,25.410000,2.972000e+01,4.954000e+01
perimeter_worst,569.0,1.072612e+02,3.360254e+01,50.410000,84.110000,97.660000,1.254000e+02,2.512000e+02
area_worst,569.0,8.805831e+02,5.693570e+02,185.200000,515.300000,686.500000,1.084000e+03,4.254000e+03
smoothness_worst,569.0,1.323686e-01,2.283243e-02,0.071170,0.116600,0.131300,1.460000e-01,2.226000e-01
compactness_worst,569.0,2.542650e-01,1.573365e-01,0.027290,0.147200,0.211900,3.391000e-01,1.058000e+00
concavity_worst,569.0,2.721885e-01,2.086243e-01,0.000000,0.114500,0.226700,3.829000e-01,1.252000e+00
concave points_worst,569.0,1.146062e-01,6.573234e-02,0.000000,0.064930,0.099930,1.614000e-01,2.910000e-01
symmetry_worst,569.0,2.900756e-01,6.186747e-02,0.156500,0.250400,0.282200,3.179000e-01,6.638000e-01
fractal_dimension_worst,569.0,8.394582e-02,1.806127e-02,0.055040,0.071460,0.080040,9.208000e-02,2.075000e-01
Unnamed: 32,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='str')

## Transform

### Data Cleaning

In [9]:
for col in ["id","Unnamed: 32"]:
    if col in df.columns:
        df = df.drop(columns=[col])

df.shape

(569, 31)

### Column Data Type fix

In [10]:
target_col = "diagnosis"
df[target_col].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [11]:
diagnosis_m = df[target_col].value_counts()['M']
diagnosis_b = df[target_col].value_counts()['B']
print(f"malignant: {(diagnosis_m * 100 / (diagnosis_m + diagnosis_b)):.2f}%")
print(f"benign: {(diagnosis_b * 100 / (diagnosis_m + diagnosis_b)):.2f}%")

malignant: 37.26%
benign: 62.74%

Convert **`B`** to **`0`**, and **`M`** to **`1`**

In [12]:
df[target_col] = df[target_col].map({"B":0, "M":1})

df[target_col].value_counts()

diagnosis
0    357
1    212
Name: count, dtype: int64

## Train / Test Split

In [13]:
X = df.drop(columns=[target_col])
y = df[target_col]

X_train, X_test, y_train, y_test = train_test_split(
    X,y,
    test_size = 0.2,
    stratify=y,
    random_state=42
)

X_train.shape, X_test.shape

((455, 30), (114, 30))

# Preprocessing

## Scaling

In [14]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled.shape, X_test_scaled.shape

((455, 30), (114, 30))

# Helper Methods

## A standard evaluation function (for all models)

In [15]:
def evaluate_model(name, model, X_tr, X_te, y_tr, y_te):
    model.fit(X_tr, y_tr)
    y_pred = model.predict(X_te)

    # Some models have predict_proba, some have decision_function
    y_score = None
    if hasattr(model, "predict_proba"):
        y_score = model.predict_proba(X_te)[:, 1]
    elif hasattr(model, "decision_function"):
        y_score = model.decision_function(X_te)

    results = {
        "model": name,
        "accuracy": accuracy_score(y_te, y_pred),
        "precision": precision_score(y_te, y_pred, zero_division=0),
        "recall": recall_score(y_te, y_pred, zero_division=0),
        "f1": f1_score(y_te, y_pred, zero_division=0),
        "roc_auc": roc_auc_score(y_te, y_score) if y_score is not None else np.nan
    }

    cm = confusion_matrix(y_te, y_pred)
    return results, cm

## Metrics Table

In [16]:
def show_metrics_table(metrics_dict):
    cleaned = {}

    for k, v in metrics_dict.items():
        if isinstance(v, np.generic):
            cleaned[k] = float(v)
        else:
            cleaned[k] = v

    df = pd.DataFrame(cleaned.items(), columns=["Metric", "Value"])
    return df

## Confusion Matrix

In [17]:
def show_confusion_matrix_table(cm):
    tn, fp, fn, tp = cm.ravel()

    df = pd.DataFrame(
        [
            [tn, fp],
            [fn, tp]
        ],
        columns=["Predicted Negative", "Predicted Positive"],
        index=["Actual Negative", "Actual Positive"]
    )

    print("\nDetails:")
    print(f"TN = {tn}")
    print(f"FP = {fp}")
    print(f"FN = {fn}")
    print(f"TP = {tp}")
    return df

# Model Training / Evaluation

## Logistic Regression

In [18]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=500,random_state=42)

res_lr, cm_lr = evaluate_model("LogisticRegression",lr, X_train_scaled, X_test_scaled, y_train, y_test)

In [19]:
show_metrics_table(res_lr)

      Metric               Value
0      model  LogisticRegression
1   accuracy            0.964912
2  precision               0.975
3     recall            0.928571
4         f1             0.95122
5    roc_auc            0.996032

In [20]:
show_confusion_matrix_table(cm_lr)

Details:
TN = 71
FP = 1
FN = 3
TP = 39

                 Predicted Negative  Predicted Positive
Actual Negative                  71                   1
Actual Positive                   3                  39

In [21]:
print(classification_report(y_test, lr.predict(X_test_scaled)))

              precision    recall  f1-score   support

           0       0.96      0.99      0.97        72
           1       0.97      0.93      0.95        42

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114

## K-Nearest Neighbors (KNN)

In [22]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5,weights="distance")

res_knn, cm_knn = evaluate_model("KNN",knn,X_train_scaled,X_test_scaled,y_train,y_test)

In [23]:
show_metrics_table(res_knn)

      Metric     Value
0      model       KNN
1   accuracy   0.95614
2  precision  0.974359
3     recall  0.904762
4         f1  0.938272
5    roc_auc  0.982474

In [24]:
show_confusion_matrix_table(cm_knn)

Details:
TN = 71
FP = 1
FN = 4
TP = 38

                 Predicted Negative  Predicted Positive
Actual Negative                  71                   1
Actual Positive                   4                  38

## Navie Bayes (Gaussian NB)

In [25]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()

res_nb, cm_nb = evaluate_model(
    "NaiveBayes", nb,
    X_train_scaled, X_test_scaled,
    y_train, y_test
)

In [26]:
show_confusion_matrix_table(cm_nb)

Details:
TN = 69
FP = 3
FN = 6
TP = 36

                 Predicted Negative  Predicted Positive
Actual Negative                  69                   3
Actual Positive                   6                  36

In [27]:
show_metrics_table(res_nb)

      Metric       Value
0      model  NaiveBayes
1   accuracy    0.921053
2  precision    0.923077
3     recall    0.857143
4         f1    0.888889
5    roc_auc    0.989087

## Decision Tree (DT)

In [28]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(max_depth=5,random_state=42)

res_dt, cm_dt = evaluate_model(
    "DecisionTree", dt,
    X_train, X_test,
    y_train, y_test
)

In [29]:
show_metrics_table(res_dt)

      Metric         Value
0      model  DecisionTree
1   accuracy      0.921053
2  precision      0.945946
3     recall      0.833333
4         f1      0.886076
5    roc_auc      0.944775

In [ ]:
show_confusion_matrix_table(cm_dt)

Details:
TN = 70
FP = 2
FN = 7
TP = 35

                 Predicted Negative  Predicted Positive
Actual Negative                  70                   2
Actual Positive                   7                  35

## Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    random_state=42,
    n_jobs=-1
)

res_rf, cm_rf = evaluate_model(
    "RandomForest", rf,
    X_train, X_test,
    y_train, y_test
)

In [ ]:
show_metrics_table(res_rf)

In [ ]:
show_confusion_matrix_table(cm_rf)

## Support Vector Machine (SVM)

In [ ]:
from sklearn.svm import SVC

svm = SVC(
    kernel="rbf",
    C=1.0,
    probability=True,
    random_state=42
)

res_svm, cm_svm = evaluate_model(
    "SVM", svm,
    X_train_scaled, X_test_scaled,
    y_train, y_test
)

In [ ]:
show_metrics_table(res_svm)

In [ ]:
show_confusion_matrix_table(cm_svm)

## AdaBoost

In [ ]:
from sklearn.ensemble import AdaBoostClassifier

ada = AdaBoostClassifier(
    n_estimators=200,
    learning_rate=0.05,
    random_state=42
)

res_ada, cm_ada = evaluate_model(
    "AdaBoost", ada,
    X_train, X_test,
    y_train, y_test
)

In [ ]:
show_metrics_table(res_ada)

In [ ]:
show_confusion_matrix_table(cm_ada)

## Gradient Boosting (GB)

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

res_gb, cm_gb = evaluate_model(
    "GradientBoosting", gb,
    X_train, X_test,
    y_train, y_test
)

In [ ]:
show_metrics_table(res_gb)

In [ ]:
show_confusion_matrix_table(cm_gb)

## XGBoost

In [ ]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=3,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric="logloss",
    random_state=42
)

res_xgb, cm_xgb = evaluate_model(
    "XGBoost", xgb,
    X_train, X_test,
    y_train, y_test
)

In [ ]:
show_metrics_table(res_xgb)

In [ ]:
show_confusion_matrix_table(cm_xgb)

## LightGBM

In [ ]:
from lightgbm import LGBMClassifier

lgbm = LGBMClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=-1,
    random_state=42,
    verbose=-1
)

res_lgbm, cm_lgbm = evaluate_model(
    "LightGBM", lgbm,
    X_train, X_test,
    y_train, y_test
)

In [ ]:
show_metrics_table(res_lgbm)

In [ ]:
show_confusion_matrix_table(cm_lgbm)

## Catboost

In [ ]:
from catboost import CatBoostClassifier

cat = CatBoostClassifier(
    n_estimators=300,
    learning_rate=0.05,
    depth=6,
    random_state=42,
    verbose=False
)

res_cat, cm_cat = evaluate_model(
    "CatBoost", cat,
    X_train, X_test,
    y_train, y_test
)

In [ ]:
show_metrics_table(res_cat)

In [ ]:
show_confusion_matrix_table(cm_cat)

# Model Comparing
## Final Comparision of all models

In [ ]:
results = pd.DataFrame([
    res_lr,
    res_knn,
    res_nb,
    res_dt,
    res_rf,
    res_svm,
    res_ada,
    res_gb,
    res_xgb,
    res_lgbm,
    res_cat
]).sort_values(by="roc_auc",ascending=False)

results

## Confusion Matrix Analysis

Confusion Matrix display function + FNR/FPR calcuation

In [ ]:
def analyze_confusion_matrix(name, cm):
    tn, fp, fn, tp = cm.ravel()

    analysis = {
        "model": name,
        "TP": tp,
        "TN": tn,
        "FP": fp,
        "FN": fn,
        "FN_rate": fn / (fn + tp),
        "FP_rate": fp / (fp + tn)
    }

    return analysis

Confusion Matrix analysis for all models

In [ ]:
cm_analysis = pd.DataFrame([
    analyze_confusion_matrix("LogisticRegression", cm_lr),
    analyze_confusion_matrix("KNN", cm_knn),
    analyze_confusion_matrix("NaiveBayes", cm_nb),
    analyze_confusion_matrix("DecisionTree", cm_dt),
    analyze_confusion_matrix("LogisticRegression", cm_lr),
    analyze_confusion_matrix("RandomForest", cm_rf),
    analyze_confusion_matrix("SVM", cm_svm),
    analyze_confusion_matrix("AdaBoost", cm_ada),
    analyze_confusion_matrix("GradientBoosting", cm_gb),
    analyze_confusion_matrix("XGBoost", cm_xgb),
    analyze_confusion_matrix("LightGBM", cm_lgbm),
    analyze_confusion_matrix("CatBoost", cm_cat)
]).sort_values(by="FN")

cm_analysis

# Feature Importance Analysis

## Feature Importance with Random Forest

In [ ]:
rf.fit(X_train,y_train)

rf_importance = pd.Series(
    rf.feature_importances_,
    index=X_train.columns
).sort_values(ascending=False)

rf_importance.head(15)

### Drawing a chart (Top 15)

In [ ]:
plt.figure()
rf_importance.head(15).plot(kind="barh")
plt.gca().invert_yaxis()
plt.title("Random Forest - Top 15 Feature Importances")
plt.show()

## Feature Importance with XGBoost

In [ ]:
xgb.fit(X_train, y_train)

xgb_importance = pd.Series(
    xgb.feature_importances_,
    index=X_train.columns
).sort_values(ascending=False)

xgb_importance.head(15)

### XGBoost Chart

In [ ]:
plt.figure()
xgb_importance.head(15).plot(kind="barh")
plt.gca().invert_yaxis()
plt.title("XGBoost - Top 15 Feature Importances")
plt.show()

## Feature Importance with LightGBM

In [ ]:
lgbm.fit(X_train, y_train)

lgbm_importance = pd.Series(
    lgbm.feature_importances_,
    index=X_train.columns
).sort_values(ascending=False)

lgbm_importance.head(15)

### LightGBM Chart

In [ ]:
plt.figure()
lgbm_importance.head(15).plot(kind="barh")
plt.gca().invert_yaxis()
plt.title("LightGBM - Top 15 Feature Importances")
plt.show()

## Comparision of important features between models

In [ ]:
comparision = pd.DataFrame({
    "RandomForest": rf_importance,
    "XGBoost": xgb_importance,
    "LightGBM": lgbm_importance
})

comparision

# Threshold Tuning

## Getting the LightGBM Output Probability

In [ ]:
lgbm.fit(X_train, y_train)

y_proba = lgbm.predict_proba(X_test)[:,1]

## Evaluation Function with threshold

In [ ]:
def evaluate_with_threshold(y_true, y_proba, threshold):
    y_pred = (y_proba >= threshold).astype(int)
    cm = confusion_matrix(y_true, y_pred)

    tn, fp, fn, tp = cm.ravel()

    return {
        "threshold": threshold,
        "TP": tp,
        "TN": tn,
        "FP": fp,
        "FN": fn,
        "recall": tp / (tp + fn),
        "precision": tp / (tp + fp) if (tp + fp) > 0 else 0,
        "fn_rate": fn / (fn + tp)
    }

## Testing Different thresholds

In [ ]:
thresholds = np.arange(0.1, 0.91, 0.05)

threshold_results = pd.DataFrame([
    evaluate_with_threshold(y_test,y_proba,t)
    for t in thresholds
])

threshold_results

### Choosing the optimal Threshold

In [ ]:
threshold_results.sort_values(by="FN")

## Final evaluation with new Threshold

In [ ]:
best_threshold = 0.10

y_predict_final = (y_proba >= best_threshold).astype(int)
cm_final = confusion_matrix(y_test,y_predict_final)

show_confusion_matrix_table(cm_final)

# Cross Validaiton with fixed threshold

In [ ]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

In [ ]:
THRESHOLD = 0.10

cv_results = []

for fold, (train_idx, val_idx) in enumerate(skf.split(X, y), start=1):
    X_tr, X_val = X.iloc[train_idx], X.iloc[val_idx]
    y_tr, y_val = y.iloc[train_idx], y.iloc[val_idx]

    model = LGBMClassifier(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=-1,
        random_state=42,
        verbose=-1
    )

    model.fit(X_tr, y_tr)

    y_proba_val = model.predict_proba(X_val)[:, 1]
    y_pred_val = (y_proba_val >= THRESHOLD).astype(int)

    tn, fp, fn, tp = confusion_matrix(y_val, y_pred_val).ravel()

    cv_results.append({
        "fold": fold,
        "TP": tp,
        "TN": tn,
        "FP": fp,
        "FN": fn,
        "recall": tp / (tp + fn),
        "precision": tp / (tp + fp) if (tp + fp) > 0 else 0,
        "fn_rate": fn / (fn + tp)
    })

cv_df = pd.DataFrame(cv_results)
cv_df

## Examining FN stability in folds

In [ ]:
cv_df[["fold","FN","recall","fn_rate"]]

In [ ]:
cv_df.describe()

Threshold = 0.10 ➡️ FN = 2

# Model Explainablility with SHAP

In [ ]:
import shap

In [ ]:
lgbm.fit(X_train, y_train)

explainer = shap.TreeExplainer(lgbm)
shap_values = explainer.shap_values(X_train)

## SHAP Summary Plot

In [ ]:
shap.summary_plot(
    shap_values,
    X_train,
    plot_type="bar"
)

## SHAP Summary (Beeswarm)

In [ ]:
shap.summary_plot(
    shap_values,
    X_train
)

# Finalize Model

In [ ]:
FINAL_THRESHOLD = 0.10

final_model = LGBMClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=-1,
    random_state=42,
    verbose=-1    
)

final_model.fit(X_train,y_train)

# Inference Function

In [ ]:
def medical_inference(model, X_input, threshold=0.10):
    """
    Medical-safe inference function.
    
    Returns:
    - prediction (0=Benign, 1=Malignant)
    - probability
    - risk_label
    """
    proba = model.predict_proba(X_input)[:, 1]
    prediction = (proba >= threshold).astype(int)

    risk_label = np.where(
        proba >= threshold,
        "High Risk (Review Required)",
        "Low Risk"
    )

    return pd.DataFrame({
        "probability_malignant": proba,
        "prediction": prediction,
        "risk_label": risk_label
    })

## Inference test on Test Set

In [ ]:
inference_result = medical_inference(
    final_model,
    X_test,
    FINAL_THRESHOLD
)

inference_result.head(5)

# Save Model

In [ ]:
import joblib

joblib.dump(final_model,"mdeical_lgbm_model.pkl")

# Load Model

In [ ]:
loaded_model = joblib.load("mdeical_lgbm_model.pkl")

In [ ]:
loaded_model